/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PanicRouteImport } from './routes/panic'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentalRouteImport } from './routes/mental'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicRoute = PanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalRoute = MentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/fitness': typeof FitnessRoute
  '/mental': typeof MentalRoute
  '/onboarding': typeof OnboardingRoute
  '/panic': typeof PanicRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/fitness': typeof FitnessRoute
  '/mental': typeof MentalRoute
  '/onboarding': typeof OnboardingRoute
  '/panic': typeof PanicRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/fitness': typeof FitnessRoute
  '/mental': typeof MentalRoute
  '/onboarding': typeof OnboardingRoute
  '/panic': typeof PanicRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/waitlist': typeof WaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/ecosystem'
    | '/fitness'
    | '/mental'
    | '/onboarding'
    | '/panic'
    | '/profile'
    | '/progress'
    | '/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/ecosystem'
    | '/fitness'
    | '/mental'
    | '/onboarding'
    | '/panic'
    | '/profile'
    | '/progress'
    | '/waitlist'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/coach'
    | '/community'
    | '/dashboard'
    | '/ecosystem'
    | '/fitness'
    | '/mental'
    | '/onboarding'
    | '/panic'
    | '/profile'
    | '/progress'
    | '/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CoachRoute: typeof CoachRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EcosystemRoute: typeof EcosystemRoute
  FitnessRoute: typeof FitnessRoute
  MentalRoute: typeof MentalRoute
  OnboardingRoute: typeof OnboardingRoute
  PanicRoute: typeof PanicRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic': {
      id: '/panic'
      path: '/panic'
      fullPath: '/panic'
      preLoaderRoute: typeof PanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental': {
      id: '/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof MentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CoachRoute: CoachRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EcosystemRoute: EcosystemRoute,
  FitnessRoute: FitnessRoute,
  MentalRoute: MentalRoute,
  OnboardingRoute: OnboardingRoute,
  PanicRoute: PanicRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
